image: "nixos/latest"
packages:
    - nixos.git
sources:
    - https://github.com/diamondburned/gotk4
tasks:
    - generate: |
        cd gotk4/
        nix-shell ./shell.nix --command 'go generate'
        # Ensure that the generated output matches.
        [[ ! $(git status -s) ]] && exit
        git status -s # report
        exit 1        # fail
    - build: |
        cd gotk4/
        nix-shell ./shell.nix --command 'go build ./...'
